### ISSUE TITLE
Contribution guide

### ISSUE THREAD

**Issue by OlivierJM** [WillzMu/Project-Zed#2]
So I wanted to contribute to the project, I forked it but I can't run it because it needs firebase.

It would be hard to contribute to it this way, the best way I can suggest is you have different branch, that runs the dummy data and doesn't need firebase to run, this way people can contribute and test that everything is okay without needing firebase.
Imagine you just want to change the css or other basic things but you can't because you need firebase.

Let me know if this kind of setup is possible, otherwise I like the project and it loos great, to me

**Comment by wilfredmulenga** [comment]
sorry took very long to get it done. hopefully it allows for more easier collaboration
