### ISSUE TITLE
Fix unwanted horizontal scroll on homepage

### ISSUE THREAD

**Issue by wilfredmulenga** [WillzMu/Project-Zed#27]
In Card.jsx there is a div tag with classes 'card-body' and 'row'. I believe the row class has a left and right margin that is causing the unwanted horizontal scroll though it could be something else.

**Comment by k9uma** [comment]
Can I claim this issue?
Also is there a contributors guide?

**Comment by wilfredmulenga** [comment]
Hey @k9uma please do. There is currently no contributor's guide. Do you have suggestions for that. I just added [Semantic](https://github.com/probot/semantic-pull-requests) pull requests hehe. So we might need to add it to the contributor's guide
