### ISSUE TITLE
One user, one like click

### ISSUE THREAD

**Issue by sikaili99** [WillzMu/Project-Zed#29]
Currently, a user can like a project as many times they can as long as they refresh the page after liking a project unlike is canceled and like is visible again.

**Comment by wilfredmulenga** [comment]
thanks for logging that. would you like to take the issue?

**Comment by wilfredmulenga** [comment]
possible way of fixing this bug is to add to the `project` object, the userUID that liked the project. Then if a user clicks on `like`, there must be a check initially to see if they liked the project before before increasing the `like` count

**Comment by wilfredmulenga** [comment]
handled the fix according to the suggestion above
