### ISSUE TITLE
The project needs a logo

### ISSUE THREAD

**Issue by sikaili99** [WillzMu/Project-Zed#30]
The project needs a logo, any designer can bring in their creative arts in this and it will be really appreciated.

**Comment by wilfredmulenga** [comment]
sorry, logo right? do you anyone willing ?

**Comment by sikaili99** [comment]
> sorry, logo right? do you know anyone willing?

Yes I meant logo, at the moment I don't know but we can ask some guys DevC group. They can help

**Comment by wilfredmulenga** [comment]
true. I have shared the project in that group

**Comment by wilfredmulenga** [comment]
Closing this issue for now
