### ISSUE TITLE
refactor class names from camel case to kebab case

### ISSUE THREAD

**Issue by wilfredmulenga** [WillzMu/Project-Zed#40]
I am a criminal for mixing up cases especially with classes. The task here is to change all class names that are camel case to kebab case.

**Comment by sourcediz** [comment]
Just to confirm are we are you wanting css classes or javascript classes?

**Comment by sourcediz** [comment]
Just to confirm thats css classes?

**Comment by Chizzoz** [comment]
> I am a criminal for mixing up cases especially with classes. The task here is to change all class names that are camel case to kebab case.

Am curious... Why to kebab case?

**Comment by wilfredmulenga** [comment]
It is common convention used and matches with the CSS properties e.g font-weight, background-color

Here is a link with more info: https://www.freecodecamp.org/news/css-naming-conventions-that-will-save-you-hours-of-debugging-35cea737d849/

**Comment by wilfredmulenga** [comment]
thanks @sourcediz  that is correct. I've gone through your PR. Thanks for your contribution!

**Comment by Chizzoz** [comment]
> It is common convention used and matches with the CSS properties e.g font-weight, background-color
> 
> Here is a link with more info: https://www.freecodecamp.org/news/css-naming-conventions-that-will-save-you-hours-of-debugging-35cea737d849/

I see, yeah, for CSS it makes perfect sense, in my mind I was thinking class name as for objects in OOP. Good move 👍
