### ISSUE TITLE
add react hooks to the code base

### ISSUE THREAD

**Issue by wilfredmulenga** [WillzMu/Project-Zed#41]
It would be good to use this project to learn how to use react hooks. It can be slowly added to the code base

**Comment by eduardoyutaka** [comment]
Hey @WillzMu! I would like create some PRs for using react hooks around the codebase, is that ok?

**Comment by wilfredmulenga** [comment]
Thanks @eduardoyutaka ! would greatly appreciate it. Let me know if there is anything else you need confirmation of.

**Comment by eduardoyutaka** [comment]
@WillzMu I have made these pull requests to work towards adding hooks to the react components

**Comment by wilfredmulenga** [comment]
Wow!! thanks @eduardoyutaka ! I will go through the PRs today

**Comment by WillzMu** [comment]
changing the priority on this issue
