### ISSUE TITLE
Add a loader

### ISSUE THREAD

**Issue by wilfredmulenga** [WillzMu/Project-Zed#5]
add a loader for database to load before site opens

**Comment by OlivierJM** [comment]
I wanted to create this issue, it will be important to add a loading message while firebase is getting ready.

**Comment by OlivierJM** [comment]
A quick fix on this line here, you can add what shows when the listOfProjects is not ready, a fancy loader would be good.
Then you can also use the new React Suspense to have a fallback UI 

https://github.com/WillzMu/projectZed/blob/7fd19fa7b2be9a83938858b8c2fd3f92aca18219/src/App.jsx#L77

**Comment by OlivierJM** [comment]
starting from this block 
https://github.com/WillzMu/projectZed/blob/7fd19fa7b2be9a83938858b8c2fd3f92aca18219/src/App.jsx#L60

Another way of doing this is to use conditional rendering at the top level, suppose you have a loader component called `<Loader />`

```Javascript
const { listOfProjects } = this.state

if(!listOfProjects.length){
   // this will only show when there is no data in the listOfProjects array
 // as the states get updated by data from firebase, this will be false
 return <Loader /> 
}
return (
   // now here you can render the list of Projects
)

```

**Comment by wilfredmulenga** [comment]
thanks, I will add that

**Comment by OlivierJM** [comment]
let me know if you need further help

**Comment by wilfredmulenga** [comment]
I have made added a loader, will upload it to the the live project once its checked out

**Comment by wilfredmulenga** [comment]
loader added. thanks Chief
